config/routes.rb
Snap::Application.routes.draw do
  resources :invitation_requests

  root :to => 'high_voltage/pages#show', id: 'splash'

  resources :clips
  match 'clips/:id/share' => 'clips#share'

end

app/models/clip.rb
class Clip < ActiveRecord::Base
  attr_accessible :date_string, :location, :speed, :time, :video_url, :video_attributes
  has_one :video, :as => :videoable, :dependent => :destroy

  accepts_nested_attributes_for :video, :allow_destroy => true  
end

app/models/invitation_request.rb
class InvitationRequest < ActiveRecord::Base
  attr_accessible :email

  validates :email, presence: true
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :videoable, :polymorphic => true
  attr_accessible :provider, :title, :description, :user_description,
                  :keywords, :duration, :date, :thumbnail_small, :is_demo_reel,
                  :thumbnail_large, :embed_url, :embed_code, :video_updated_at,
                  :url, :imdb
  before_save :movie_details, :if => :url?
  scope :real, where("thumbnail_small is NOT NULL")

  def movie_details
    video = VideoInfo.get(self.url)
    if video.present?
      self.provider        = video.provider     
      self.title           = video.title  
      self.description     = video.description 
      self.keywords        = video.keywords      
      self.duration        = video.duration   
      self.date            = video.date       
      self.thumbnail_small = video.thumbnail_small
      self.thumbnail_large = video.thumbnail_large
      self.embed_url       = video.embed_url      
      self.embed_code      = video.embed_code
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  # GET /clips
  # GET /clips.json
  def index
    @clips = Clip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clips }
    end
  end

  # GET /clips/1
  # GET /clips/1.json
  def show
    @clip = Clip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @clip }
    end
  end

  # GET /clips/new
  # GET /clips/new.json
  def new
    @clip = Clip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @clip }
    end
  end

  # GET /clips/1/edit
  def edit
    @clip = Clip.find(params[:id])
  end

  # POST /clips
  # POST /clips.json
  def create
    @clip = Clip.new(params[:clip])

    respond_to do |format|
      if @clip.save
        format.html { redirect_to @clip, notice: 'Clip was successfully created.' }
        format.json { render json: @clip, status: :created, location: @clip }
      else
        format.html { render action: "new" }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clips/1
  # PUT /clips/1.json
  def update
    @clip = Clip.find(params[:id])

    respond_to do |format|
      if @clip.update_attributes(params[:clip])
        format.html { redirect_to @clip, notice: 'Clip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clips/1
  # DELETE /clips/1.json
  def destroy
    @clip = Clip.find(params[:id])
    @clip.destroy

    respond_to do |format|
      format.html { redirect_to clips_url }
      format.json { head :no_content }
    end
  end


  def share
    @clip = Clip.find(params[:id])

  end
end

app/controllers/invitation_requests_controller.rb
class InvitationRequestsController < ApplicationController
  respond_to :json

  def index
    @invitation_requests = InvitationRequest.all.order("created_at DESC")
    respond_with(@invitation_requests)
  end

  def create
    @invitation_request = InvitationRequest.create(invitation_request_params)
    respond_with(@invitation_request)
  end

  def destroy
    @invitation_request = InvitationRequest.find(params[:id])
    @invitation_request.destroy
    respond_with(@invitation_request)
  end

  private

  def invitation_request_params
    params[:invitation_request]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/views/clips/_form.html.erb
<%= form_for(@clip) do |f| %>
  <% if @clip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clip.errors.count, "error") %> prohibited this clip from being saved:</h2>

      <ul>
      <% @clip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :speed %><br />
    <%= f.text_field :speed %>
  </div>
  <div class="field">
    <%= f.label :date_string %><br />
    <%= f.text_field :date_string %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.fields_for :video, @clip.video || Video.new do |video| %>
      <%= f.label :url, "Video URL" %><br />
      <%= video.text_field(:url) %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clips/edit.html.erb
<h1>Editing clip</h1>

<%= render 'form' %>

<%= link_to 'Show', @clip %> |
<%= link_to 'Back', clips_path %>

app/views/clips/index.html.erb
<%= stylesheet_link_tag "clips/manifest.css" %>

<div class='container-fluid'>
  <div class='row-fluid'>
    <div class='span12'>
      <h3>My snaps</h3>
      <% @clips.each do |clip| %>
        <a href='<%= clip_path(clip) %>'>
          
          <div class='row-fluid clip'>
            <div class='span5 clip_tumbnail'>
              <img src="<%= clip.video.thumbnail_large %>">
            </div>
           
            <div class='span7 clip_details'>
              <div class='row-fluid'>
                <div class='span12 clip_detail date bold'>
                  <%= time_ago_in_words (Time.parse(clip.date_string)) %> ago
                </div>

                <div class='span12 clip_detail time bold'>
                  <%= clip.time %>
                </div>
                <div class='span12 clip_detail speed_loc light'>
                  <%= clip.speed %> mph &nbsp;&nbsp;<div class='location-marker'></div> <%= clip.location %>
                </div>
                <div class='span12 clip_detail'>
                  <%= link_to 'Show', clip %>
                  <%= link_to 'Edit', edit_clip_path(clip) %>
                  <%= link_to 'Destroy', clip, method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
              </div>
            </div>
          </div>
        </a>
      <% end %>

    </div>
  </div>
</div>

<br />

<%= link_to 'New Clip', new_clip_path %>

app/views/clips/new.html.erb
<h1>New clip</h1>

<%= render 'form' %>

<%= link_to 'Back', clips_path %>

app/views/clips/share.html.erb
<div class='container-fluid'>
  <div class='row-fluid'>
    <div class='back_btn pull-left'>
      <a href='/clips/<%= @clip.id %>'> BACK</a>
    </div>
    <div class='share_head pull-left' >
      Share Video
    </div>
  </div>

  <div class='row-fluid'>
    <div class='share_btn box' data-type='box'></div>
    <div class='share_btn tube' data-type='tube'></div>
  </div>

</div>


<script type="text/javascript">
$(document).ready(function(){
  $('body').on('click', '.share_btn', function(){
    btn = $(event.target)
    type = btn.attr('data-type')

    btn.addClass('loading')

    setTimeout(function(){
      btn.addClass('done');
      setTimeout(function(){
        window.location='/clips/<%= @clip.id %>';
      }, 2000);
    },3000);
  })
})
</script>

app/views/clips/show.html.erb
<p id="notice"><%= notice %></p>

<div class='container-fluid show'>
  <div class='row-fluid clip'>
    <div class='span12'>
      <div class='row-fluid'>
        
        <div class='span2 grey'>
          
          <div class='row-fluid '>
            <div class='span10 offset1'>
              <span class='pull-left light'>
                <div class='sun'></div> fair
              </span>

              <span class='pull-right light'>
                73<sup>o</sup> F
              </span>
            </div>
          </div>
          
          <div class='row-fluid'>
            <div class='span10 offset1 date light' style='margin-top: -10px;'>
              <%= @clip.date_string %>
            </div>
          </div>
          
          <div class='row-fluid'>
            <div class='span10 offset1 time light'>
              <%= @clip.time %>
            </div>
          </div>
          <div class='row-fluid' >
            <div class='span10 offset1' style='margin-top: -10px;margin-bottom: -17px;'>
              <div class='row-fluid'>
                <div class='speed span5' id='car_speed'>
                  35
                </div>
                <div class='span3 offset1 meter_div'>
                  <div class='row-fluid light'>
                    <div class='span12'>
                      mph
                    </div>
                  </div>

                  <div class='row-fluid'>
                    <div class='span12'>
                      <div class='meter-icon'></div>
                    </div>
                  </div>

                </div>
              </div>    
            </div>
          </div>
          <div class='row-fluid share-div'>
            <a href='/clips/<%= @clip.id %>/share'>
              <div class='span5 offset4 light'>
                share
              </div>
            </a>
          </div>
          <div class='row-fluid'>
            <div class='span12 map_div'>
              <img src="/assets/map-sample.png">
              <div id='car_top'></div>
            </div>
          </div>
        </div>
        <div class='video_div span10'>
          <iframe id="player1" src="<%= @clip.video.embed_url %>?api=1&player_id=player1&title=0&byline=0&portrait=0&autoplay=1" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
      </div>

    </div>
  </div>
</div>

<%= link_to 'Edit', edit_clip_path(@clip) %> |
<%= link_to 'Back', clips_path %>


<script type="text/javascript">
$(document).ready(function(){
  window.speed = 35;
  window.car_top = 118;

  var iframe = $('#player1')[0],
  player = $f(iframe),
  status = $('.status');

  // When the player is ready, add listeners for pause, finish, and playProgress
  player.addEvent('ready', function() {
      player.addEvent('finish', onFinish);
      player.addEvent('play', onPlay);
      player.addEvent('playProgress', onPlayProgress);
  });

  function onFinish(id) {

  }

  function onPlay (id) {
    console.log('started')
  }

  function onPlayProgress(data, id) {
    speed_div = $('#car_speed')
    speed_div.html
    
    to_show = window.speed - 1
    
    if (to_show < 18){
      speed_div.addClass('orange');
    }

    if(to_show <= 10){
      speed_div.addClass('red').removeClass('orange');
    }
    
    if (parseInt(to_show) >= 0){
      speed_div.html(to_show);
      window.speed = to_show
      $('#car_top').css('top', (window.car_top - 2) + 'px');
      window.car_top = window.car_top - 2
    }
    
  }
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snap</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/splash.html.haml
#splash
  #content
    .brand Roadview
    %p.motto Playback & share anything from <br/> the road.
    %p.details Save last 60 seconds off your front-view camera <br/> with a voice command

    %form.invitation_request
      %p Enter your email for early access
      = text_field_tag "email"
      = button_tag "REQUEST", class: 'submit'